#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

# daemons and stuff
#twmnd &
#dunst -fn -*-terminus-medium-r-*-*-12-*-*-*-*-*-*-* -lb \#222222 -lf \#ababab -nb \#222222 -nf \#ababab -cb \#ababab -cf \#141414 -to 3 -mod mod4 -key c -geometry 0x1 &
dunst &
#mpd &
#scmpc &
xset s off &
xset b off &
xset -dpms &

hsetroot -solid '#333333'

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt
#hc keybind $Mod-x spawn dmenu_run -fn -*-terminus-medium-r-*-*-12-*-*-*-*-*-*-* -nb \#222222 -nf \#ababab -sb \#007700 -sf \#222222
hc keybind $Mod-x spawn dmenu_run -fn Terminus:size=8 -nb \#222222 -nf \#ababab -sb \#007700 -sf \#222222
hc keybind XF86AudioMute spawn amixer sset Master,0 toggle
hc keybind XF86AudioRaiseVolume spawn amixer sset Master,0 1%+
hc keybind XF86AudioLowerVolume spawn amixer sset Master,0 1%-
hc keybind $Mod-z spawn sleep_screen 

# tags
TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1
hc keybind $Mod-comma  use_index -1
hc keybind $Mod-Right use_index +1
hc keybind $Mod-Left  use_index -1

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right
# Use and move to floating monitor
hc keybind $Mod-b use f
hc keybind $Mod-Shift-b move f
# Use q3terminal script for dropdown
hc keybind $Mod-grave spawn q3terminal 0
hc keybind $Mod-Shift-grave move 0

# colors
hc set frame_border_active_color '#007700'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#333333'
hc set frame_bg_active_color '#333333'
hc set frame_bg_transparent 1 
hc set frame_border_width 0
hc set window_border_width 1
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#007700'
hc set always_show_frame 1
hc set window_gap 0
hc set frame_gap 0

hc set focus_follows_mouse 0
#hc set auto_detect_monitors 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class~'(.*[Cc]hromium.*)' ewmhrequests=off
hc rule class~'(.*[Cc]hrome.*)' ewmhrequests=off
hc rule class~'(.*[Gg]vbam.*)' ewmhrequests=off

#Move modal dialogs to float window
hc rule --windowtype=_NET_WM_WINDOW_TYPE_DIALOG --focus=on --tag="f"
hc rule --windowrole=pop-up --focus=on --tag="f"

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
#hc remove_monitor 1
#hc move_monitor 0 1280x1024+0+0
#hc add_monitor 1280x1024+1280+0

# This is just because I switch from laptop screen to external monitor
# with different resolutions. Grabs the proper string from xrandr!
geom=$(xrandr | grep current | awk '{print $8$9$10}')

## New floating monitor stuff
hc detect_monitors
hc use 1 # Use tag 1 on the first monitor
hc add "f" # Adds a tag labeled f
hc add_monitor ${geom%?}+0+0 "f" # Adds a monitor, using tag "f"
hc raise_monitor 1 # Puts the floating monitor above the tiling one
hc lock_tag 1 # Locks the tag on the floating monitor to "f"

hc floating f on # Oops, don't forget to set "f" to float

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done

